name: mindraw

networks:
  appnet:
    driver: bridge

services:
  mindraw-app:
    image: registry.ware.cloud/mindraw-app
    ports:
      - "80:80"
    # env_file:
    #   - .env.production
    environment:
      VITE_APP_BACKEND_V2_GET_URL: http://localhost:8080/api/v2/scenes/
      VITE_APP_BACKEND_V2_POST_URL: http://localhost:8080/api/v2/scenes/
      VITE_APP_LIBRARY_URL: https://libraries.excalidraw.com
      VITE_APP_LIBRARY_BACKEND: https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries
      VITE_APP_WS_SERVER_URL: http://localhost:8081/
      VITE_APP_STORAGE_BACKEND: "http"
      VITE_APP_HTTP_STORAGE_BACKEND_URL: http://localhost:8080/api/v2
    networks:
      - appnet
    restart: unless-stopped

  mindraw-storage-backend:
    image: registry.ware.cloud/mindraw-storage-backend
    ports:
      - "8080:8080"
    environment:
      STORAGE_URI: redis://redis:6379
    networks:
      - appnet
    restart: unless-stopped

  mindraw-room:
    image: registry.ware.cloud/mindraw-room
    ports:
      - "8081:80"
    networks:
      - appnet
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - appnet
    restart: unless-stopped
